// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title MockUltraVerifier
 * @notice Mock verifier for testing purposes
 * @dev This simulates the UltraVerifier generated by Noir
 * Replace with actual generated verifier in production
 */
contract MockUltraVerifier {
    /**
     * @notice Mock verification function
     * @dev In tests, this always returns true
     * The real UltraVerifier will properly verify ZK proofs
     */
    function verify(
        bytes calldata _proof,
        bytes32[] calldata _publicInputs
    ) external pure returns (bool) {
        // Mock implementation - always returns true for testing
        // Real verifier will have complex verification logic
        require(_proof.length > 0, "Empty proof");
        require(_publicInputs.length > 0, "No public inputs");
        return true;
    }
}
